@host = http://localhost:8080/api
###
@authHost = http://localhost:8080/auth

### get All
GET {{host}}/users HTTP/1.1
Authorization: admin:admin

### Login
POST {{authHost}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin",
    "password": "admin"
}

### save one Users

POST {{host}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "Amit",
    "id":0,
    "age": 23,
    "gender":"Male"
}

### get one user
GET {{host}}/users/2 HTTP/1.1

### update given user
PUT {{host}}/users/5 HTTP/1.1
Content-Type: application/json

{
    "name" : "Raju",
    "age": 24
}