@host = http://localhost:8080/api
###
@authHost = http://localhost:8080/auth

### Bearer Token
@auth = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxMTM2NDk1NCwiaWF0IjoxNzExMzQ2OTU0fQ.kYvHAm8ZO_kb4_9VDhd77gBcrl-gn64fliyp0msRcg8WI0OkJIy6M4Ci26ePpXXbE1ZZh6EAdU_m35oX8e3eZA


### get All
GET {{host}}/users HTTP/1.1
Authorization: {{auth}}

### Login
POST {{authHost}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin",
    "password": "admin"
}

### save one Users

POST {{host}}/users HTTP/1.1
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "Amit",
    "id":0,
    "age": 23,
    "gender":"Male"
}

### get one user
GET {{host}}/users/2 HTTP/1.1
Authorization: {{auth}}

### update given user
PUT {{host}}/users/3 HTTP/1.1
Authorization: {{auth}}
Content-Type: application/json

{
    "email": "a@in.com",
    "phoneNumber": "9873431289"
}